# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{human_codes}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Danger Canty"]
  s.date = %q{2010-07-12}
  s.description = %q{Convert integers to human-readable compressed alphanumeric strings and back. Lets humans enter very long integers quickly. Uses base-31 compression of integers.}
  s.email = %q{rubygems@6brand.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Manifest.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "human_codes.gemspec",
     "init.rb",
     "lib/human_codes.rb",
     "rails/init.rb",
     "test/test_human_codes.rb"
  ]
  s.homepage = %q{http://github.com/JackDanger/human_codes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Convert integers to human-readable compressed alphanumeric strings and back. Lets humans enter very long integers quickly.}
  s.test_files = [
    "test/test_human_codes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

